_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
