# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/precise-data-447807-t6/my-mlops-repository/image-1
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
