_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 50
                - 55
                - 105
            "2":
                - 1
                - 50
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
