_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 50
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
        visualize:
            roc:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curve
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
epochs:
    value: 2
lr:
    value: 0.001
